import {defineArrayMember, defineField, defineType} from 'sanity'
import {
  CONTENT_SEO_FIELDSETS,
  GROUP_MODULAR_SECTIONS,
  modularSectionsField,
  sectionDividerFieldset,
  singletonSeoField,
} from '../shared/singletonContentFields'
import {GROUP_SEO} from '../shared/fieldGroups'
import {studioListMedia} from '../shared/studioListMedia'
import {portableHeadlineField} from '../shared/inlineHeroHeadlineField'

const GROUP_HERO = {name: 'hero', title: 'Hero', default: true}
const GROUP_READINESS = {name: 'readiness', title: 'Feature cards (image panels)'}
const GROUP_INFOGRAPHIC = {name: 'infographic', title: 'Infographic'}
const GROUP_TIMELINE = {name: 'timeline', title: 'Timeline'}
const GROUP_CTA = {name: 'cta', title: 'Bottom CTA'}

export const diagnosticLandingPage = defineType({
  name: 'diagnosticLandingPage',
  title: 'Startup diagnostic landing (/startup-diagnostic)',
  type: 'document',
  groups: [GROUP_HERO, GROUP_READINESS, GROUP_INFOGRAPHIC, GROUP_TIMELINE, GROUP_CTA, GROUP_MODULAR_SECTIONS, GROUP_SEO],
  fieldsets: [
    sectionDividerFieldset('heroDivider', 'Hero'),
    sectionDividerFieldset('readinessDivider', 'Feature cards (image panels)'),
    sectionDividerFieldset('infographicDivider', 'Infographic'),
    sectionDividerFieldset('timelineDivider', 'Timeline'),
    sectionDividerFieldset('ctaDivider', 'Bottom CTA'),
    ...CONTENT_SEO_FIELDSETS,
  ],
  fields: [
    defineField({name: 'title', type: 'string', initialValue: 'Startup Diagnostic', group: 'hero', fieldset: 'heroDivider'}),
    defineField({
      name: 'surveyNote',
      title: 'Survey page note (editors)',
      type: 'text',
      rows: 3,
      readOnly: true,
      initialValue:
        'The interactive survey at /diagnostic-survey is driven by the app (questions & scoring). Edit this landing page for marketing copy; contact engineering to change survey logic.',
      group: 'hero',
      fieldset: 'heroDivider',
    }),
    defineField({
      name: 'heroBadgeLabel',
      title: 'Hero badge',
      type: 'string',
      initialValue: 'LAUNCH READINESS',
      group: 'hero',
      fieldset: 'heroDivider',
    }),
    portableHeadlineField({group: 'hero', fieldset: 'heroDivider'}),
    defineField({name: 'heroSubtitle', title: 'Hero subtitle', type: 'text', rows: 3, group: 'hero', fieldset: 'heroDivider'}),
    defineField({name: 'heroImage', title: 'Hero image', type: 'image', options: {hotspot: true}, group: 'hero', fieldset: 'heroDivider'}),
    defineField({name: 'heroImageUrl', title: 'Hero image URL (fallback)', type: 'string', group: 'hero', fieldset: 'heroDivider'}),
    defineField({
      name: 'heroPrimaryCtaLabel',
      title: 'Primary CTA label',
      type: 'string',
      initialValue: 'Begin Free Assessment',
      group: 'hero',
      fieldset: 'heroDivider',
    }),
    defineField({
      name: 'heroPrimaryCtaHref',
      title: 'Primary CTA link',
      type: 'string',
      initialValue: '/diagnostic-survey',
      group: 'hero',
      fieldset: 'heroDivider',
    }),
    defineField({
      name: 'readinessTitle',
      title: 'Section heading',
      type: 'string',
      description: 'Headline above the four expandable image panels.',
      initialValue: 'A complete readiness map',
      group: 'readiness',
      fieldset: 'readinessDivider',
    }),
    defineField({
      name: 'readinessDescription',
      title: 'Section intro',
      type: 'text',
      rows: 3,
      description: 'Short paragraph under the heading.',
      group: 'readiness',
      fieldset: 'readinessDivider',
    }),
    defineField({
      name: 'readinessFeatures',
      title: 'Feature cards (4 image panels)',
      type: 'array',
      description: 'Up to four cards with background image, title, description, and optional button.',
      group: 'readiness',
      fieldset: 'readinessDivider',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'readinessFeature',
          fields: [
            defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
            defineField({name: 'description', type: 'text', rows: 3, validation: (Rule) => Rule.required()}),
            defineField({name: 'image', type: 'image', options: {hotspot: true}}),
            defineField({name: 'imageSrc', title: 'Image URL (fallback)', type: 'string'}),
            defineField({name: 'buttonLabel', title: 'Optional button label', type: 'string'}),
            defineField({
              name: 'buttonPath',
              title: 'Optional button link',
              type: 'string',
              description: 'Internal path, e.g. /diagnostic-survey',
            }),
          ],
          preview: {select: {title: 'title', subtitle: 'description', media: 'image'}},
        }),
      ],
    }),
    defineField({
      name: 'infographicTitle',
      title: 'Section title',
      type: 'string',
      initialValue: 'No stone left unturned',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({name: 'infographicBody', title: 'Section body', type: 'text', rows: 4, group: 'infographic', fieldset: 'infographicDivider'}),
    defineField({
      name: 'infographicTopWeaknessLabel',
      title: 'Top weakness label',
      type: 'string',
      initialValue: 'Regulatory Strategy',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'infographicTopWeaknessScore',
      title: 'Top weakness score (%)',
      type: 'number',
      initialValue: 32,
      validation: (Rule) => Rule.min(0).max(100),
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'infographicGapLabel',
      title: 'Gap severity label',
      type: 'string',
      initialValue: 'Critical Gap',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'infographicAdvisorMatchLabel',
      title: 'Advisor match label',
      type: 'string',
      initialValue: 'Vetted Advisor Match',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'infographicAdvisorRole',
      title: 'Advisor role (blurred preview)',
      type: 'string',
      initialValue: 'Regulatory Director',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'infographicAdvisorSubtitle',
      title: 'Advisor subtitle',
      type: 'string',
      initialValue: 'Ex-FDA Reviewer',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'infographicBlobRoadmap',
      title: 'Blob: Personalized roadmap',
      type: 'string',
      initialValue: 'Personalized Roadmap',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'infographicBlobAdvisors',
      title: 'Blob: Matched advisors',
      type: 'string',
      initialValue: 'Matched Advisors',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'infographicBlobBlindSpot',
      title: 'Blob: Blind spot discovery',
      type: 'string',
      initialValue: 'Blind Spot Discovery',
      group: 'infographic',
      fieldset: 'infographicDivider',
    }),
    defineField({
      name: 'timelineTitle',
      title: 'Timeline heading',
      type: 'string',
      initialValue: 'Survey to insights in 15 minutes',
      group: 'timeline',
      fieldset: 'timelineDivider',
    }),
    defineField({name: 'timelineSubheading', title: 'Timeline subheading', type: 'text', rows: 2, group: 'timeline', fieldset: 'timelineDivider'}),
    defineField({
      name: 'timelineSteps',
      title: 'Timeline steps',
      type: 'array',
      group: 'timeline',
      fieldset: 'timelineDivider',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'title', type: 'string', validation: (Rule) => Rule.required()}),
            defineField({name: 'description', type: 'text', rows: 2, validation: (Rule) => Rule.required()}),
          ],
          preview: {select: {title: 'title', subtitle: 'description'}},
        }),
      ],
    }),
    defineField({
      name: 'ctaTitle',
      title: 'CTA headline',
      type: 'string',
      initialValue: 'Benchmark your startup today',
      group: 'cta',
      fieldset: 'ctaDivider',
    }),
    defineField({name: 'ctaBody', title: 'CTA body', type: 'text', rows: 2, group: 'cta', fieldset: 'ctaDivider'}),
    defineField({
      name: 'ctaPrimaryLabel',
      title: 'Primary CTA label',
      type: 'string',
      initialValue: 'Take the Diagnostic',
      group: 'cta',
      fieldset: 'ctaDivider',
    }),
    defineField({
      name: 'ctaPrimaryHref',
      title: 'Primary CTA link',
      type: 'string',
      initialValue: '/diagnostic-survey',
      group: 'cta',
      fieldset: 'ctaDivider',
    }),
    defineField({
      name: 'ctaSecondaryLabel',
      title: 'Secondary CTA label',
      type: 'string',
      initialValue: 'Join as Member',
      group: 'cta',
      fieldset: 'ctaDivider',
    }),
    defineField({
      name: 'ctaSecondaryHref',
      title: 'Secondary CTA link',
      type: 'string',
      initialValue: '/apply',
      group: 'cta',
      fieldset: 'ctaDivider',
    }),
    modularSectionsField({
      description:
        'Optional modular blocks rendered on /startup-diagnostic after the timeline and before the footer CTA band.',
    }),
    singletonSeoField,
  ],
  preview: {
    prepare() {
      return {
        title: 'Startup diagnostic landing',
        subtitle: '/startup-diagnostic',
        media: studioListMedia.document,
      }
    },
  },
})
