import {defineField, defineType} from 'sanity'
import {logoMarqueeField} from '../objects/logoMarqueeItem'
import {CONTENT_SEO_FIELDSETS, modularSectionsField, singletonSeoField} from '../shared/singletonContentFields'
import {
  NETWORK_PAGE_GROUPS,
  networkCtaFields,
  networkEligibilityItemMember,
  networkEngageBandFields,
  networkExploreCardMember,
  networkFeatureItemMember,
  networkHeroFields,
  networkJourneyStepMember,
  networkMembershipPathStepMember,
  networkWhyRelliaFields,
} from '../shared/networkPageFields'

export const networkFoundersPage = defineType({
  name: 'networkFoundersPage',
  title: 'Network — Founders page (/founders)',
  type: 'document',
  groups: NETWORK_PAGE_GROUPS,
  fieldsets: CONTENT_SEO_FIELDSETS,
  fields: [
    defineField({name: 'title', type: 'string', initialValue: 'Founders', group: 'hero'}),
    ...networkHeroFields,
    defineField({
      name: 'eligibilityTitle',
      title: 'Eligibility section title',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'eligibilityDescription',
      title: 'Eligibility section description',
      type: 'text',
      rows: 2,
      group: 'content',
    }),
    defineField({
      name: 'eligibilityItems',
      title: 'Eligibility cards',
      type: 'array',
      of: [networkEligibilityItemMember],
      group: 'content',
    }),
    ...networkEngageBandFields,
    ...networkWhyRelliaFields,
    defineField({
      name: 'showJourneySection',
      title: 'Show trajectory section',
      type: 'boolean',
      initialValue: true,
      group: 'content',
    }),
    defineField({
      name: 'journeyTitle',
      title: 'Trajectory section title',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'journeyHelpBadge',
      title: 'Trajectory bottom badge',
      type: 'string',
      description: 'Pill label above the Rellia help cards (e.g. “We help with”).',
      group: 'content',
    }),
    defineField({
      name: 'journeyHelpHeading',
      title: 'Trajectory bottom heading',
      type: 'text',
      rows: 2,
      description: 'Supporting line next to the bottom badge.',
      group: 'content',
    }),
    defineField({
      name: 'journeySteps',
      title: 'Trajectory timeline steps',
      type: 'array',
      of: [networkJourneyStepMember],
      group: 'content',
    }),
    defineField({name: 'exploreTitle', title: 'Explore section title', type: 'string', group: 'content'}),
    defineField({name: 'exploreSubtitle', title: 'Explore section subtitle', type: 'text', rows: 2, group: 'content'}),
    defineField({
      name: 'exploreCards',
      title: 'Explore cards',
      type: 'array',
      of: [networkExploreCardMember],
      group: 'content',
    }),
    defineField({name: 'deeperHelpTitle', title: 'Consulting section title', type: 'string', group: 'content'}),
    defineField({name: 'deeperHelpSubtitle', title: 'Consulting section subtitle', type: 'text', rows: 2, group: 'content'}),
    defineField({
      name: 'deeperHelpFeatures',
      title: 'Consulting feature cards',
      type: 'array',
      of: [networkFeatureItemMember],
      group: 'content',
    }),
    defineField({name: 'deeperHelpCtaLabel', title: 'Consulting CTA label', type: 'string', group: 'content'}),
    defineField({name: 'deeperHelpCtaHref', title: 'Consulting CTA link', type: 'string', group: 'content'}),
    defineField({
      name: 'membershipPathTitle',
      title: 'Membership path heading',
      type: 'string',
      description: 'Heading for the “From application to your first warm intro” timeline section.',
      group: 'content',
    }),
    defineField({
      name: 'membershipPathSubtitle',
      title: 'Membership path subheading',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'membershipPathSteps',
      title: 'Membership path steps',
      type: 'array',
      of: [networkMembershipPathStepMember],
      group: 'content',
    }),
    defineField({
      name: 'deeperHelpBackgroundImage',
      title: 'Consulting section background',
      type: 'image',
      options: {hotspot: true},
      group: 'content',
    }),
    defineField({
      name: 'deeperHelpBackgroundImageUrl',
      title: 'Consulting background URL (fallback)',
      type: 'string',
      group: 'content',
    }),
    ...networkCtaFields,
    {...logoMarqueeField, group: 'content'},
    modularSectionsField({
      description:
        'Optional modular blocks rendered on /founders after the main page sections and before the footer CTA band.',
    }),
    singletonSeoField,
  ],
})
