import {defineField, defineType} from 'sanity'
import {logoMarqueeField} from '../objects/logoMarqueeItem'
import {CONTENT_SEO_FIELDSETS, singletonSeoField} from '../shared/singletonContentFields'
import {
  NETWORK_PAGE_GROUPS,
  networkCtaFields,
  networkEligibilityItemMember,
  networkEngageBandFields,
  networkExploreCardMember,
  networkFeatureItemMember,
  networkHeroFields,
  networkJourneyStepMember,
  networkWhyRelliaFields,
} from '../shared/networkPageFields'

export const networkFoundersPage = defineType({
  name: 'networkFoundersPage',
  title: 'Network — Founders page (/founders)',
  type: 'document',
  groups: NETWORK_PAGE_GROUPS,
  fieldsets: CONTENT_SEO_FIELDSETS,
  fields: [
    defineField({name: 'title', type: 'string', initialValue: 'Founders', group: 'hero'}),
    ...networkHeroFields,
    defineField({
      name: 'eligibilityTitle',
      title: 'Eligibility section title',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'eligibilityDescription',
      title: 'Eligibility section description',
      type: 'text',
      rows: 2,
      group: 'content',
    }),
    defineField({
      name: 'eligibilityItems',
      title: 'Eligibility cards',
      type: 'array',
      of: [networkEligibilityItemMember],
      group: 'content',
    }),
    ...networkEngageBandFields,
    ...networkWhyRelliaFields,
    defineField({name: 'journeyTitle', title: 'Journey section title', type: 'string', group: 'content'}),
    defineField({name: 'journeySubtitle', title: 'Journey section subtitle', type: 'text', rows: 2, group: 'content'}),
    defineField({
      name: 'journeySteps',
      title: 'Journey timeline steps',
      type: 'array',
      of: [networkJourneyStepMember],
      group: 'content',
    }),
    defineField({name: 'exploreTitle', title: 'Explore section title', type: 'string', group: 'content'}),
    defineField({name: 'exploreSubtitle', title: 'Explore section subtitle', type: 'text', rows: 2, group: 'content'}),
    defineField({
      name: 'exploreCards',
      title: 'Explore cards',
      type: 'array',
      of: [networkExploreCardMember],
      group: 'content',
    }),
    defineField({name: 'deeperHelpTitle', title: 'Consulting section title', type: 'string', group: 'content'}),
    defineField({name: 'deeperHelpSubtitle', title: 'Consulting section subtitle', type: 'text', rows: 2, group: 'content'}),
    defineField({
      name: 'deeperHelpFeatures',
      title: 'Consulting feature cards',
      type: 'array',
      of: [networkFeatureItemMember],
      group: 'content',
    }),
    defineField({name: 'deeperHelpCtaLabel', title: 'Consulting CTA label', type: 'string', group: 'content'}),
    defineField({name: 'deeperHelpCtaHref', title: 'Consulting CTA link', type: 'string', group: 'content'}),
    ...networkCtaFields,
    {...logoMarqueeField, group: 'content'},
    singletonSeoField,
  ],
})
