import {defineField, defineType} from 'sanity'
import {documentGroups, FIELDSET_SEO} from '../shared/fieldGroups'
import {singletonLayoutFields} from '../shared/singletonLayoutFields'
import {singletonPublishingAtTop} from '../shared/documentTopFields'
import {publishingGroup} from '../shared/pageVisibilityFields'

const legacyMembershipFields = [
  defineField({
    name: 'badge',
    type: 'string',
    title: 'Eyebrow label (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'headline',
    type: 'string',
    title: 'Main headline (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'introCheckout',
    type: 'text',
    rows: 2,
    title: 'Intro — embedded checkout (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'introFallback',
    type: 'text',
    rows: 2,
    title: 'Intro — payment links (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'introFallbackError',
    type: 'text',
    rows: 2,
    title: 'Intro — checkout error (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'successTitle',
    type: 'string',
    title: 'Success headline (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'successBody',
    type: 'text',
    rows: 3,
    title: 'Success message (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'heroHeadlinePortable',
    title: 'Hero headline (legacy)',
    type: 'inlineHeroHeadline',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'heroSubheadline',
    type: 'text',
    rows: 2,
    title: 'Hero subheadline (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'imageCardBadge',
    type: 'string',
    title: 'Image card eyebrow (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'imageCardHeadlinePortable',
    title: 'Image card headline (legacy)',
    type: 'inlineHeroHeadline',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'imageCardImage',
    title: 'Image card upload (legacy)',
    type: 'image',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'imageCardSrc',
    type: 'string',
    title: 'Image card path (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({name: 'imageCardAlt', type: 'string', title: 'Image card alt (legacy)', hidden: true, readOnly: true, group: 'content'}),
  defineField({
    name: 'highlightBenefits',
    type: 'array',
    title: 'Image card highlights (legacy)',
    of: [{type: 'string'}],
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'pricingMonthlyBadge',
    type: 'string',
    title: 'Monthly badge (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'pricingAnnualBadge',
    type: 'string',
    title: 'Annual badge (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'pricingPerSuffix',
    type: 'string',
    title: 'Pricing suffix (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
  defineField({
    name: 'popularLabel',
    type: 'string',
    title: 'Popular label (legacy)',
    hidden: true,
    readOnly: true,
    group: 'content',
  }),
]

export const paymentPage = defineType({
  name: 'paymentPage',
  title: 'Payment page (/membership)',
  type: 'document',
  groups: [publishingGroup, ...documentGroups.filter((g) => g.name !== 'publishing' && g.name !== 'seo')],
  fields: [
    ...singletonPublishingAtTop,
    defineField({
      name: 'benefitsPanelHeadline',
      type: 'string',
      title: 'Left panel headline',
      description: 'Teal benefits card headline (e.g. Join the network today).',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'benefitsTitle',
      type: 'string',
      title: 'Benefits title (fallback)',
      description: 'Used only if left panel headline is empty.',
      group: 'content',
    }),
    defineField({
      name: 'benefits',
      type: 'array',
      title: 'Benefits list',
      of: [{type: 'string'}],
      group: 'content',
      validation: (Rule) => Rule.min(1),
    }),
    defineField({
      name: 'choosePlanHeadline',
      type: 'string',
      title: 'Plan picker headline',
      initialValue: 'Choose your plan',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'pricingMonthlyAmount',
      type: 'string',
      title: 'Monthly price (e.g. $30)',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'pricingAnnualAmount',
      type: 'string',
      title: 'Annual price (e.g. $25)',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'pricingMonthlyDiscountEnabled',
      type: 'boolean',
      title: 'Monthly — show compare price',
      initialValue: false,
      group: 'content',
    }),
    defineField({
      name: 'pricingMonthlyCompareAmount',
      type: 'string',
      title: 'Monthly compare price',
      group: 'content',
    }),
    defineField({
      name: 'pricingAnnualDiscountEnabled',
      type: 'boolean',
      title: 'Annual — show compare price',
      initialValue: false,
      group: 'content',
    }),
    defineField({
      name: 'pricingAnnualCompareAmount',
      type: 'string',
      title: 'Annual compare price',
      group: 'content',
    }),
    defineField({
      name: 'monthlyProceedLabel',
      type: 'string',
      title: 'Monthly CTA label',
      group: 'content',
    }),
    defineField({
      name: 'annualProceedLabel',
      type: 'string',
      title: 'Annual CTA label',
      group: 'content',
    }),
    defineField({
      name: 'discountBannerEnabled',
      type: 'boolean',
      title: 'Show promo block',
      initialValue: true,
      group: 'content',
    }),
    defineField({
      name: 'discountBannerBadge',
      type: 'string',
      title: 'Promo pill label',
      group: 'content',
    }),
    defineField({
      name: 'discountBannerTitle',
      type: 'string',
      title: 'Promo headline (legacy fallback)',
      group: 'content',
    }),
    defineField({
      name: 'discountBannerSubtitle',
      type: 'text',
      rows: 2,
      title: 'Discount code',
      description: 'Copied when user taps Apply code.',
      group: 'content',
    }),
    defineField({
      name: 'discountBannerApplyLabel',
      type: 'string',
      title: 'Apply code button label',
      group: 'content',
    }),
    defineField({
      name: 'promoPillEnabled',
      type: 'boolean',
      title: 'Show promo pill',
      initialValue: true,
      group: 'content',
    }),
    defineField({
      name: 'promoMessage',
      type: 'text',
      rows: 2,
      title: 'Promo message',
      description: 'Use {code} where the discount code should appear.',
      group: 'content',
    }),
    defineField({
      name: 'questionsTitle',
      type: 'string',
      title: 'Bottom CTA headline',
      initialValue: 'Questions about membership?',
      group: 'content',
    }),
    defineField({
      name: 'questionsBody',
      type: 'text',
      rows: 3,
      title: 'Bottom CTA body',
      initialValue:
        "Have questions about the membership, billing, or benefits? We're here to help you get the most out of the Rellia network.",
      group: 'content',
    }),
    defineField({
      name: 'questionsContactLabel',
      type: 'string',
      title: 'Bottom CTA primary button label',
      initialValue: 'Contact us',
      group: 'content',
    }),
    defineField({
      name: 'questionsContactPath',
      type: 'string',
      title: 'Bottom CTA primary button path',
      initialValue: '/contact',
      group: 'content',
    }),
    defineField({
      name: 'questionsFaqLabel',
      type: 'string',
      title: 'Bottom CTA secondary button label',
      initialValue: 'View FAQ',
      group: 'content',
    }),
    defineField({
      name: 'questionsFaqPath',
      type: 'string',
      title: 'Bottom CTA secondary button path',
      initialValue: '/faq',
      group: 'content',
    }),
    ...legacyMembershipFields,
    ...singletonLayoutFields,
  ],
})
