import {defineField, defineType} from 'sanity'
import {documentGroups, FIELDSET_SEO} from '../shared/fieldGroups'
import {singletonLayoutFields} from '../shared/singletonLayoutFields'

export const paymentPage = defineType({
  name: 'paymentPage',
  title: 'Payment page (/membership)',
  type: 'document',
  groups: documentGroups,
  fieldsets: [FIELDSET_SEO],
  fields: [
    defineField({name: 'badge', type: 'string', title: 'Eyebrow label', group: 'content'}),
    defineField({name: 'headline', type: 'string', title: 'Main headline', group: 'content'}),
    defineField({
      name: 'introFallback',
      type: 'text',
      rows: 2,
      title: 'Intro (payment links)',
      description:
        'Copy above the monthly/annual buttons. Explains that checkout opens in a new tab (Stripe Payment Link).',
      group: 'content',
    }),
    defineField({name: 'benefitsTitle', type: 'string', title: 'Benefits section title', group: 'content'}),
    defineField({
      name: 'benefits',
      type: 'array',
      title: 'Benefits',
      of: [{type: 'string'}],
      group: 'content',
    }),
    defineField({name: 'successTitle', type: 'string', title: 'Success headline', group: 'content'}),
    defineField({name: 'successBody', type: 'text', rows: 3, title: 'Success message', group: 'content'}),
    defineField({
      name: 'discountBannerEnabled',
      type: 'boolean',
      title: 'Show discount banner',
      initialValue: false,
      group: 'content',
    }),
    defineField({
      name: 'discountBannerTitle',
      type: 'string',
      title: 'Discount banner — headline',
      group: 'content',
    }),
    defineField({
      name: 'discountBannerSubtitle',
      type: 'text',
      rows: 2,
      title: 'Discount banner — supporting text',
      group: 'content',
    }),
    defineField({
      name: 'discountBannerBadge',
      type: 'string',
      title: 'Discount banner — pill label (e.g. LIMITED OFFER)',
      group: 'content',
    }),
    defineField({
      name: 'discountBannerApplyLabel',
      type: 'string',
      title: 'Discount banner — apply button label',
      group: 'content',
    }),
    defineField({
      name: 'discountBannerApplyHref',
      type: 'string',
      title: 'Discount banner — apply button URL (optional)',
      group: 'content',
    }),
    defineField({
      name: 'heroHeadlinePortable',
      title: 'Hero headline',
      type: 'inlineHeroHeadline',
      description: 'Use Mint on the emphasized phrase.',
      group: 'content',
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'heroSubheadline', type: 'text', rows: 2, title: 'Hero — subheadline', group: 'content'}),
    defineField({name: 'imageCardBadge', type: 'string', title: 'Image card — eyebrow', group: 'content'}),
    defineField({
      name: 'imageCardHeadlinePortable',
      title: 'Image card headline',
      type: 'inlineHeroHeadline',
      group: 'content',
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'imageCardImage',
      title: 'Image card — uploaded image',
      type: 'image',
      options: {hotspot: true},
      description: 'Upload preferred. Falls back to "Image card — image path" below.',
      group: 'content',
    }),
    defineField({
      name: 'imageCardSrc',
      type: 'string',
      title: 'Image card — image path (fallback, e.g. /images/... )',
      group: 'content',
    }),
    defineField({name: 'imageCardAlt', type: 'string', title: 'Image card — alt text', group: 'content'}),
    defineField({
      name: 'highlightBenefits',
      type: 'array',
      title: 'Image card — four highlight points (bottom row)',
      of: [{type: 'string'}],
      group: 'content',
    }),
    defineField({name: 'pricingMonthlyBadge', type: 'string', title: 'Pricing — monthly badge', group: 'content'}),
    defineField({name: 'pricingAnnualBadge', type: 'string', title: 'Pricing — annual badge', group: 'content'}),
    defineField({
      name: 'pricingMonthlyAmount',
      type: 'string',
      title: 'Pricing — monthly price (e.g. $30)',
      group: 'content',
    }),
    defineField({
      name: 'pricingAnnualAmount',
      type: 'string',
      title: 'Pricing — annual price (e.g. $25)',
      group: 'content',
    }),
    defineField({
      name: 'pricingPerSuffix',
      type: 'string',
      title: 'Pricing — suffix (e.g. /month)',
      group: 'content',
    }),
    defineField({name: 'popularLabel', type: 'string', title: 'Pricing — popular label', group: 'content'}),
    defineField({name: 'monthlyProceedLabel', type: 'string', title: 'Pricing — monthly CTA', group: 'content'}),
    defineField({name: 'annualProceedLabel', type: 'string', title: 'Pricing — annual CTA', group: 'content'}),
    defineField({name: 'questionsTitle', type: 'string', title: 'Questions strip — headline', group: 'content'}),
    defineField({name: 'questionsFaqLabel', type: 'string', title: 'Questions strip — FAQ button', group: 'content'}),
    defineField({name: 'questionsFaqPath', type: 'string', title: 'Questions strip — FAQ path', group: 'content'}),
    defineField({
      name: 'questionsContactLabel',
      type: 'string',
      title: 'Questions strip — contact button',
      group: 'content',
    }),
    defineField({
      name: 'questionsContactPath',
      type: 'string',
      title: 'Questions strip — contact path',
      group: 'content',
    }),
    ...singletonLayoutFields,
    defineField({name: 'seo', type: 'seo', group: 'seo', fieldset: 'seo'}),
  ],
})
