import { useMemo, useState, useEffect, type ReactNode } from "react"
import { Link, useSearchParams } from "react-router-dom"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { Inbox, Search, Stethoscope } from "lucide-react"
import { supabase } from "@/lib/supabase"
import AdminPageReveal from "@/components/admin/AdminPageReveal"
import AdminRecordList from "@/components/admin/AdminRecordList"
import AdminSelectFilter from "@/components/admin/AdminSelectFilter"
import AdminSubmissionStatusSelect from "@/components/admin/AdminSubmissionStatusSelect"
import AdminSubmissionStatusFilter from "@/components/admin/AdminSubmissionStatusFilter"
import { adminWarningBannerClass, adminSegmentedTabCountClass, adminSegmentedTabsListClass, adminSegmentedTabTriggerClass, adminInboxContactTableClass, adminInboxDiagnosticTableClass, adminToolbarSearchInputClass } from "@/components/admin/adminThemeClasses"
import AdminNoteIconButton from "@/components/admin/AdminNoteIconButton"
import AdminDeleteIconButton from "@/components/admin/AdminDeleteIconButton"
import AdminCompactEmptyState from "@/components/admin/AdminCompactEmptyState"
import AdminSubmissionStatusBadge from "@/components/admin/AdminSubmissionStatusBadge"
import AdminTableMultilineText from "@/components/admin/AdminTableMultilineText"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  countByStatusFilter,
  formatAdminDate,
  matchesStatusFilter,
  submissionStatusUpdatePayload,
  type StatusFilterValue,
  type SubmissionStatus,
} from "@/lib/adminSubmissionStatus"
import {
  contactDisplayName,
  contactTypeLabel,
  fetchContactSubmissions,
  fetchDiagnosticSubmissions,
  isAutoGeneratedContactMessage,
  parseModalSubmissionSource,
  type CompanyProfileRow,
  type ContactRow,
} from "@/lib/adminSubmissions"
import { cn } from "@/lib/utils"
import type { AdminTableColumn } from "@/components/admin/AdminDataTable"

type SubmissionTab = "contact" | "diagnostic"

type ContactSourceFilter = "all" | "contact" | "investor" | "modal"

const CONTACT_SOURCE_OPTIONS: { value: ContactSourceFilter; label: string }[] = [
  { value: "all", label: "All types" },
  { value: "contact", label: "Contact" },
  { value: "investor", label: "Investor" },
  { value: "modal", label: "Priority modal" },
]

const UNRESOLVED_COUNT_KEY = ["admin-unresolved-submissions-count"] as const

const contactMessagePreview = (row: ContactRow): string => {
  if (row.submission_type === "modal" && isAutoGeneratedContactMessage(row.message)) {
    const source = parseModalSubmissionSource(row.message)
    return source ? `Priority modal · ${source}` : "Priority modal submission"
  }
  if (isAutoGeneratedContactMessage(row.message)) return ""
  return row.message
}

const diagnosticMessagePreview = (row: CompanyProfileRow): string =>
  row.description?.trim() || row.diagnostic_response?.summary?.trim() || ""

const matchesSearch = (haystack: string, query: string) => {
  const q = query.trim().toLowerCase()
  if (!q) return true
  return haystack.toLowerCase().includes(q)
}

const AdminInboxPage = () => {
  const queryClient = useQueryClient()
  const [searchParams, setSearchParams] = useSearchParams()
  const tabParam = searchParams.get("tab")
  const tab: SubmissionTab = tabParam === "diagnostic" ? "diagnostic" : "contact"
  const sourceParam = searchParams.get("source")
  const contactSource: "all" | "contact" | "investor" | "modal" =
    sourceParam === "investor"
      ? "investor"
      : sourceParam === "contact"
        ? "contact"
        : sourceParam === "modal"
          ? "modal"
          : "all"
  const [statusFilter, setStatusFilter] = useState<StatusFilterValue>("all")
  const [searchQuery, setSearchQuery] = useState(() => searchParams.get("q") ?? "")
  const [levelFilter, setLevelFilter] = useState<string>("all")
  const [updatingId, setUpdatingId] = useState<string | null>(null)
  const [statusWritesEnabled, setStatusWritesEnabled] = useState(true)

  useEffect(() => {
    const q = searchParams.get("q") ?? ""
    setSearchQuery((current) => (current === q ? current : q))
  }, [searchParams])

  const setTab = (next: SubmissionTab) => {
    setSearchParams((prev) => {
      const nextParams = new URLSearchParams(prev)
      nextParams.set("tab", next)
      if (next !== "contact") nextParams.delete("source")
      return nextParams
    }, { replace: true })
    setStatusFilter("all")
    setSearchQuery("")
    setLevelFilter("all")
  }

  const setContactSource = (next: "all" | "contact" | "investor" | "modal") => {
    setSearchParams((prev) => {
      const nextParams = new URLSearchParams(prev)
      nextParams.set("tab", "contact")
      if (next === "all") nextParams.delete("source")
      else nextParams.set("source", next)
      return nextParams
    }, { replace: true })
  }

  const contactsQuery = useQuery({ queryKey: ["admin-contact-submissions"], queryFn: fetchContactSubmissions })
  const diagnosticsQuery = useQuery({ queryKey: ["admin-company-profiles"], queryFn: fetchDiagnosticSubmissions })

  const contactRows = contactsQuery.data ?? []
  const diagnosticRows = diagnosticsQuery.data ?? []
  const isLoading = tab === "contact" ? contactsQuery.isLoading : diagnosticsQuery.isLoading
  const error = tab === "contact" ? contactsQuery.error : diagnosticsQuery.error

  const statusCounts = useMemo(
    () => (tab === "contact" ? countByStatusFilter(contactRows) : countByStatusFilter(diagnosticRows)),
    [tab, contactRows, diagnosticRows],
  )

  const contactSourceCounts = useMemo(() => {
    const counts = { all: contactRows.length, contact: 0, investor: 0, modal: 0 }
    contactRows.forEach((row) => {
      const type = String(row.submission_type ?? "").trim().toLowerCase()
      if (type === "investor") counts.investor += 1
      else if (type === "modal") counts.modal += 1
      else counts.contact += 1
    })
    return counts
  }, [contactRows])

  const countDiagnosticLevel = (lvl: string) => {
    if (lvl === "all") return diagnosticRows.length
    return diagnosticRows.filter(
      (row) => String(row.stage ?? "").trim().toLowerCase() === lvl.trim().toLowerCase(),
    ).length
  }

  const filteredContactRows = useMemo(
    () =>
      [...contactRows]
        .filter((row) => matchesStatusFilter(row, statusFilter))
        .filter((row) => {
          if (contactSource === "all") return true
          const type = String(row.submission_type ?? "").trim().toLowerCase()
          if (contactSource === "investor") return type === "investor"
          if (contactSource === "modal") return type === "modal"
          return type === "contact" || (type !== "investor" && type !== "modal")
        })
        .filter((row) =>
          matchesSearch(
            [
              contactDisplayName(row),
              row.email,
              row.company ?? "",
              contactTypeLabel(row),
              contactMessagePreview(row),
              row.admin_note ?? "",
            ].join(" "),
            searchQuery,
          ),
        )
        .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()),
    [contactRows, statusFilter, searchQuery, contactSource],
  )

  const filteredDiagnosticRows = useMemo(
    () =>
      [...diagnosticRows]
        .filter((row) => matchesStatusFilter(row, statusFilter))
        .filter((row) => {
          if (levelFilter === "all") return true
          return String(row.stage ?? "").trim().toLowerCase() === levelFilter.trim().toLowerCase()
        })
        .filter((row) =>
          matchesSearch(
            [
              row.name,
              row.work_email,
              row.company_name,
              row.stage ?? "",
              diagnosticMessagePreview(row),
              row.admin_note ?? "",
            ].join(" "),
            searchQuery,
          ),
        )
        .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()),
    [diagnosticRows, statusFilter, searchQuery, levelFilter],
  )

  const diagnosticLevels = useMemo(() => {
    const list = ["all", "Idea / Discovery", "Prototype / MVP", "Pilot / Seed", "Early Growth (Series A+)", "Scale-up"]
    diagnosticRows.forEach((row) => {
      if (row.stage) {
        const stageTrimmed = row.stage.trim()
        if (!list.some((item) => item.toLowerCase() === stageTrimmed.toLowerCase())) {
          list.push(stageTrimmed)
        }
      }
    })
    return list
  }, [diagnosticRows])

  const invalidateSubmissionQueries = () => {
    void queryClient.invalidateQueries({ queryKey: UNRESOLVED_COUNT_KEY })
  }

  const handleContactStatus = async (contactId: string, newStatus: SubmissionStatus) => {
    if (!statusWritesEnabled) return
    setUpdatingId(contactId)
    const { error: updateError } = await supabase
      .from("contact_responses")
      .update(submissionStatusUpdatePayload(newStatus))
      .eq("id", contactId)
    setUpdatingId(null)
    if (updateError) {
      if (updateError.message.includes("status") || updateError.message.includes("policy")) {
        setStatusWritesEnabled(false)
      }
      return
    }
    void queryClient.invalidateQueries({ queryKey: ["admin-contact-submissions"] })
    invalidateSubmissionQueries()
  }

  const handleDiagnosticStatus = async (profileId: string, newStatus: SubmissionStatus) => {
    if (!statusWritesEnabled) return
    setUpdatingId(profileId)
    const { error: updateError } = await supabase
      .from("company_profiles")
      .update(submissionStatusUpdatePayload(newStatus))
      .eq("id", profileId)
    setUpdatingId(null)
    if (updateError) {
      if (updateError.message.includes("status") || updateError.message.includes("policy")) {
        setStatusWritesEnabled(false)
      }
      return
    }
    void queryClient.invalidateQueries({ queryKey: ["admin-company-profiles"] })
    invalidateSubmissionQueries()
  }

  const handleContactDelete = async (contactId: string) => {
    const { error: deleteError } = await supabase.from("contact_responses").delete().eq("id", contactId)
    if (deleteError) return
    void queryClient.invalidateQueries({ queryKey: ["admin-contact-submissions"] })
    invalidateSubmissionQueries()
  }

  const handleDiagnosticDelete = async (profileId: string) => {
    const { error: deleteError } = await supabase.from("company_profiles").delete().eq("id", profileId)
    if (deleteError) return
    void queryClient.invalidateQueries({ queryKey: ["admin-company-profiles"] })
    invalidateSubmissionQueries()
  }

  const contactColumns: AdminTableColumn<ContactRow>[] = [
    {
      key: "name",
      header: "Name",
      className: "w-[12%]",
      cell: (row) => (
        <Link to={`/admin/contacts/${row.id}`} className="font-medium text-rellia-teal hover:underline dark:text-rellia-mint">
          {contactDisplayName(row)}
        </Link>
      ),
    },
    {
      key: "type",
      header: "Type",
      className: "w-[8%] whitespace-nowrap",
      cell: (row) => <span className="text-muted-foreground">{contactTypeLabel(row)}</span>,
    },
    {
      key: "email",
      header: "Email",
      className: "w-[14%]",
      cell: (row) => <span className="break-all">{row.email}</span>,
    },
    {
      key: "company",
      header: "Company",
      className: "w-[10%]",
      cell: (row) => <span className="block truncate text-muted-foreground">{row.company || "—"}</span>,
    },
    {
      key: "message",
      header: "Message",
      className: "w-[26%]",
      cell: (row) => (
        <AdminTableMultilineText value={contactMessagePreview(row)} className="w-full" />
      ),
    },
    {
      key: "date",
      header: "Received",
      className: "w-[10%] whitespace-nowrap",
      cell: (row) => <span className="text-muted-foreground">{formatAdminDate(row.created_at)}</span>,
    },
    {
      key: "status",
      header: "Status",
      className: "w-[9%] whitespace-nowrap",
      cell: (row) => {
        const status = (row.status ?? "New") as SubmissionStatus
        return statusWritesEnabled ? (
          <AdminSubmissionStatusSelect
            value={status}
            disabled={updatingId === row.id}
            ariaLabel={`Status for ${row.first_name}`}
            onValueChange={(value) => void handleContactStatus(row.id, value)}
          />
        ) : (
          <AdminSubmissionStatusBadge status={status} />
        )
      },
    },
    {
      key: "actions",
      header: "Actions",
      className: "w-[11%] whitespace-nowrap",
      cell: (row) => (
        <div className="flex items-start justify-start gap-0.5">
          <AdminNoteIconButton
            table="contact_responses"
            submissionId={row.id}
            note={row.admin_note}
            onSaved={() => void queryClient.invalidateQueries({ queryKey: ["admin-contact-submissions"] })}
          />
          <AdminDeleteIconButton
            label="Delete contact submission?"
            description="This permanently removes the message from your inbox."
            onConfirm={() => void handleContactDelete(row.id)}
          />
        </div>
      ),
    },
  ]

  const diagnosticColumns: AdminTableColumn<CompanyProfileRow>[] = [
    {
      key: "name",
      header: "Founder",
      className: "w-[11%]",
      cell: (row) => (
        <Link to={`/admin/companies/${row.id}`} className="font-medium text-rellia-teal hover:underline dark:text-rellia-mint">
          {row.name}
        </Link>
      ),
    },
    {
      key: "company",
      header: "Company",
      className: "w-[10%]",
      cell: (row) => <span className="block truncate">{row.company_name}</span>,
    },
    {
      key: "email",
      header: "Email",
      className: "w-[14%]",
      cell: (row) => <span className="break-all text-muted-foreground">{row.work_email}</span>,
    },
    {
      key: "stage",
      header: "Stage",
      className: "w-[9%]",
      cell: (row) => <span className="block truncate text-muted-foreground">{row.stage || "—"}</span>,
    },
    {
      key: "message",
      header: "Message",
      className: "w-[26%]",
      cell: (row) => (
        <AdminTableMultilineText value={diagnosticMessagePreview(row)} className="w-full" />
      ),
    },
    {
      key: "date",
      header: "Received",
      className: "w-[10%] whitespace-nowrap",
      cell: (row) => <span className="text-muted-foreground">{formatAdminDate(row.created_at)}</span>,
    },
    {
      key: "status",
      header: "Status",
      className: "w-[9%] whitespace-nowrap",
      cell: (row) => {
        const status = (row.status ?? "New") as SubmissionStatus
        return statusWritesEnabled ? (
          <AdminSubmissionStatusSelect
            value={status}
            disabled={updatingId === row.id}
            ariaLabel={`Status for ${row.company_name}`}
            onValueChange={(value) => void handleDiagnosticStatus(row.id, value)}
          />
        ) : (
          <AdminSubmissionStatusBadge status={status} />
        )
      },
    },
    {
      key: "actions",
      header: "Actions",
      className: "w-[11%] whitespace-nowrap",
      cell: (row) => (
        <div className="flex items-start justify-start gap-0.5">
          <AdminNoteIconButton
            table="company_profiles"
            submissionId={row.id}
            note={row.admin_note}
            onSaved={() => void queryClient.invalidateQueries({ queryKey: ["admin-company-profiles"] })}
          />
          <AdminDeleteIconButton
            label="Delete diagnostic submission?"
            description="This removes the company profile and linked diagnostic response."
            onConfirm={() => void handleDiagnosticDelete(row.id)}
          />
        </div>
      ),
    },
  ]

  const renderList = () => {
    if (isLoading) {
      return (
        <div className="space-y-3 py-2">
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-16 rounded-xl" />
          ))}
        </div>
      )
    }

    if (error) {
      return (
        <p className="rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 font-urbanist text-sm text-destructive">
          Failed to load submissions: {error instanceof Error ? error.message : "Unknown error"}
        </p>
      )
    }

    const rows = tab === "contact" ? filteredContactRows : filteredDiagnosticRows
    const emptyIcon = tab === "contact" ? Inbox : Stethoscope

    if (rows.length === 0) {
      return (
        <AdminCompactEmptyState
          icon={emptyIcon}
          title="No submissions match your filters"
          description={
            statusFilter === "all" && !searchQuery.trim()
              ? tab === "contact"
                ? "Contact and investor messages will appear here."
                : "Startup diagnostic submissions will appear here."
              : "Try clearing the search or status filter."
          }
        />
      )
    }

    const listShell = (content: ReactNode) => (
      <div className="overflow-hidden rounded-xl border border-border bg-card shadow-sm [&_ul]:p-3 [&_ul]:md:p-0">
        {content}
      </div>
    )

    if (tab === "contact") {
      return listShell(
        <AdminRecordList
          rows={filteredContactRows}
          getRowKey={(row) => row.id}
          columns={contactColumns}
          tableClassName={adminInboxContactTableClass}
          mobileFields={[
            {
              label: "Name",
              value: (row) => (
                <Link to={`/admin/contacts/${row.id}`} className="font-medium text-rellia-teal hover:underline">
                  {contactDisplayName(row)}
                </Link>
              ),
            },
            { label: "Type", value: (row) => contactTypeLabel(row) },
            { label: "Email", value: (row) => row.email },
            { label: "Message", value: (row) => contactMessagePreview(row) || "—" },
            {
              label: "Status",
              value: (row) => {
                const status = (row.status ?? "New") as SubmissionStatus
                return statusWritesEnabled ? (
                  <AdminSubmissionStatusSelect
                    value={status}
                    disabled={updatingId === row.id}
                    ariaLabel={`Status for ${row.first_name}`}
                    onValueChange={(value) => void handleContactStatus(row.id, value)}
                  />
                ) : (
                  <AdminSubmissionStatusBadge status={status} />
                )
              },
            },
          ]}
          mobileActions={(row) => (
            <div className="flex items-center gap-0.5">
              <AdminNoteIconButton
                table="contact_responses"
                submissionId={row.id}
                note={row.admin_note}
                onSaved={() => void queryClient.invalidateQueries({ queryKey: ["admin-contact-submissions"] })}
              />
              <AdminDeleteIconButton
                label="Delete contact submission?"
                description="This permanently removes the message from your inbox."
                onConfirm={() => void handleContactDelete(row.id)}
              />
            </div>
          )}
        />,
      )
    }

    return listShell(
      <AdminRecordList
        rows={filteredDiagnosticRows}
        getRowKey={(row) => row.id}
        columns={diagnosticColumns}
        tableClassName={adminInboxDiagnosticTableClass}
        mobileFields={[
          {
            label: "Founder",
            value: (row) => (
              <Link to={`/admin/companies/${row.id}`} className="font-medium text-rellia-teal hover:underline">
                {row.name}
              </Link>
            ),
          },
          { label: "Company", value: (row) => row.company_name },
          { label: "Email", value: (row) => row.work_email },
          { label: "Message", value: (row) => diagnosticMessagePreview(row) || "—" },
          {
            label: "Status",
            value: (row) => {
              const status = (row.status ?? "New") as SubmissionStatus
              return statusWritesEnabled ? (
                <AdminSubmissionStatusSelect
                  value={status}
                  disabled={updatingId === row.id}
                  ariaLabel={`Status for ${row.company_name}`}
                  onValueChange={(value) => void handleDiagnosticStatus(row.id, value)}
                />
              ) : (
                <AdminSubmissionStatusBadge status={status} />
              )
            },
          },
        ]}
        mobileActions={(row) => (
          <div className="flex items-center gap-0.5">
            <AdminNoteIconButton
              table="company_profiles"
              submissionId={row.id}
              note={row.admin_note}
              onSaved={() => void queryClient.invalidateQueries({ queryKey: ["admin-company-profiles"] })}
            />
            <AdminDeleteIconButton
              label="Delete diagnostic submission?"
              description="This removes the company profile and linked diagnostic response."
              onConfirm={() => void handleDiagnosticDelete(row.id)}
            />
          </div>
        )}
      />,
    )
  }

  return (
    <div>
      <AdminPageReveal>
      {!statusWritesEnabled ? (
        <p className={cn("mb-4", adminWarningBannerClass)}>
          Status updates need Supabase policies. Run{" "}
          <code className="text-xs">scripts/supabase_admin_policies.sql</code> in the SQL editor. If the inbox is
          empty after login, run{" "}
          <code className="text-xs">scripts/supabase_revert_admin_role_policies.sql</code> when admin-role RLS was
          enabled.
        </p>
      ) : null}

      <Tabs value={tab} onValueChange={(value) => setTab(value as SubmissionTab)} className="space-y-4">
        <TabsList className={adminSegmentedTabsListClass}>
          <div className="grid h-full w-full grid-cols-2 items-center">
            <TabsTrigger value="contact" className={adminSegmentedTabTriggerClass}>
              <span className="inline-flex items-center gap-2">
                Web forms
                <span className={adminSegmentedTabCountClass}>{contactRows.length}</span>
              </span>
            </TabsTrigger>
            <TabsTrigger value="diagnostic" className={adminSegmentedTabTriggerClass}>
              <span className="inline-flex items-center gap-2">
                Diagnostic Surveys
                <span className={adminSegmentedTabCountClass}>{diagnosticRows.length}</span>
              </span>
            </TabsTrigger>
          </div>
        </TabsList>

        <div className="flex flex-col gap-3">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-3">
            <div className="relative min-w-0 w-full flex-1">
              <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" aria-hidden />
              <Input
                type="search"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder={tab === "contact" ? "Search name, email, company…" : "Search founder, company, email…"}
                className={cn("h-10 w-full pl-9", adminToolbarSearchInputClass)}
                aria-label="Search submissions"
              />
            </div>
            <div className="flex w-auto max-w-[9rem] shrink-0 self-start sm:max-w-none sm:self-auto">
              {tab === "contact" ? (
                <AdminSelectFilter
                  value={contactSource}
                  onChange={setContactSource}
                  options={CONTACT_SOURCE_OPTIONS.map((option) => ({
                    ...option,
                    count: contactSourceCounts[option.value],
                  }))}
                  ariaLabel="Filter by submission type"
                />
              ) : (
                <AdminSelectFilter
                  value={levelFilter}
                  onChange={setLevelFilter}
                  options={diagnosticLevels.map((lvl) => ({
                    value: lvl,
                    label: lvl === "all" ? "All levels" : lvl,
                    count: countDiagnosticLevel(lvl),
                  }))}
                  ariaLabel="Filter by diagnostic level"
                />
              )}
            </div>
          </div>
          <AdminSubmissionStatusFilter
            value={statusFilter}
            onChange={setStatusFilter}
            counts={statusCounts}
          />
        </div>

        <TabsContent value="contact" className="mt-0">
          {renderList()}
        </TabsContent>
        <TabsContent value="diagnostic" className="mt-0">
          {renderList()}
        </TabsContent>
      </Tabs>
      </AdminPageReveal>
    </div>
  )
}

export default AdminInboxPage
