import { useState } from "react"
import { Link, useNavigate, useParams } from "react-router-dom"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { supabase } from "@/lib/supabase"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import AdminSubmissionStatusSelect from "@/components/admin/AdminSubmissionStatusSelect"
import AdminPageReveal from "@/components/admin/AdminPageReveal"
import AdminDeleteSubmissionButton from "@/components/admin/AdminDeleteSubmissionButton"
import AdminMailtoButton from "@/components/admin/AdminMailtoButton"
import AdminSubmissionNoteEditor from "@/components/admin/AdminSubmissionNoteEditor"
import { adminBackLinkClass, adminErrorBannerClass, adminInternalNotePanelClass, adminPageHeaderDividerClass, adminPageTitleClass, adminSubmissionTypeChipClass } from "@/components/admin/adminThemeClasses"
import { cn } from "@/lib/utils"
import {
  formatAdminDateLong,
  statusBadgeClass,
  submissionStatusUpdatePayload,
  type SubmissionStatus,
} from "@/lib/adminSubmissionStatus"
import type { ContactSubmission } from "@/pages/admin/AdminContactList"
import {
  contactDisplayName,
  isAutoGeneratedContactMessage,
  parseModalSubmissionSource,
} from "@/lib/adminSubmissions"
import { ArrowLeft } from "lucide-react"

const fetchContact = async (id: string): Promise<ContactSubmission> => {
  const { data, error } = await supabase.from("contact_responses").select("*").eq("id", id).single()
  if (error) throw error
  return data as ContactSubmission
}

const AdminContactDetail = () => {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [updating, setUpdating] = useState(false)
  const [statusWritesEnabled, setStatusWritesEnabled] = useState(true)

  const { data, isLoading, error } = useQuery({
    queryKey: ["admin-contact", id],
    queryFn: () => fetchContact(id!),
    enabled: !!id,
  })

  const handleStatusChange = async (newStatus: SubmissionStatus) => {
    if (!id || !statusWritesEnabled) return
    setUpdating(true)
    const { error: updateError } = await supabase
      .from("contact_responses")
      .update(submissionStatusUpdatePayload(newStatus))
      .eq("id", id)
    setUpdating(false)
    if (updateError) {
      if (updateError.message.includes("status") || updateError.message.includes("policy")) {
        setStatusWritesEnabled(false)
      }
      return
    }
    void queryClient.invalidateQueries({ queryKey: ["admin-contact", id] })
    void queryClient.invalidateQueries({ queryKey: ["admin-contact-submissions"] })
    void queryClient.invalidateQueries({ queryKey: ["admin-dashboard-overview"] })
  }

  const handleDelete = async () => {
    if (!id) return
    const { error: deleteError } = await supabase.from("contact_responses").delete().eq("id", id)
    if (deleteError) return
    void queryClient.invalidateQueries({ queryKey: ["admin-contact-submissions"] })
    void queryClient.invalidateQueries({ queryKey: ["admin-dashboard-overview"] })
    navigate("/admin/inbox?tab=contact", { replace: true })
  }

  if (isLoading) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-6 w-32" />
        <Skeleton className="h-40 rounded-2xl" />
      </div>
    )
  }

  if (error || !data) {
    return (
      <div className="space-y-4">
        <Link
          to="/admin/inbox?tab=contact"
          className={adminBackLinkClass}
        >
          <ArrowLeft className="h-4 w-4" aria-hidden />
          All contact submissions
        </Link>
        <p className={adminErrorBannerClass}>
          Failed to load submission.
        </p>
      </div>
    )
  }

  const status = (data.status ?? "New") as SubmissionStatus
  const hasStatusField = "status" in data
  const submissionType = (data as ContactSubmission & { submission_type?: string }).submission_type
  const isInvestor = submissionType === "investor"
  const isModal = submissionType === "modal"
  const modalHeading = isModal ? parseModalSubmissionSource(data.message) : null
  const showMessage = !isAutoGeneratedContactMessage(data.message)
  const displayName = contactDisplayName(data as ContactSubmission & { submission_type?: string })
  const mailSubject = isInvestor
    ? "Re: Rellia Health pitch events"
    : isModal
      ? `Re: ${modalHeading || "Rellia Health priority modal"}`
      : `Re: Your message to Rellia Health`
  const mailBody = `Hi ${data.first_name},\n\n`

  return (
    <div className="space-y-6">
      <AdminPageReveal>
      <Link
        to="/admin/inbox?tab=contact"
        className={adminBackLinkClass}
      >
        <ArrowLeft className="h-4 w-4" aria-hidden />
        All contact submissions
      </Link>
      </AdminPageReveal>

      <AdminPageReveal delay={0.06}>
      <div className="space-y-6">
      <article className="overflow-hidden rounded-2xl border border-border bg-card/90 shadow-sm">
        <div className={cn("bg-gradient-to-r from-rellia-mint/12 to-white px-5 py-5 md:px-6 dark:to-card/90", adminPageHeaderDividerClass)}>
          <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <h1 className={cn("font-host-grotesk text-xl font-bold md:text-2xl", adminPageTitleClass)}>
                {displayName}
                {isInvestor ? (
                  <span className={cn("ml-2", adminSubmissionTypeChipClass)}>
                    Investor
                  </span>
                ) : null}
                {isModal ? (
                  <span className={cn("ml-2", adminSubmissionTypeChipClass)}>
                    Priority modal
                  </span>
                ) : null}
              </h1>
              <p className="mt-1 font-urbanist text-sm text-muted-foreground">{data.email}</p>
              <p className="font-urbanist text-sm text-muted-foreground">{formatAdminDateLong(data.created_at)}</p>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              {hasStatusField && statusWritesEnabled ? (
                <AdminSubmissionStatusSelect
                  value={status}
                  disabled={updating}
                  ariaLabel={`Status for ${data.first_name} ${data.last_name}`}
                  onValueChange={(value) => void handleStatusChange(value)}
                />
              ) : (
                <Badge
                  variant="outline"
                  className={`rounded-full font-urbanist text-sm ${statusBadgeClass(status)}`}
                >
                  {status}
                </Badge>
              )}
              <AdminDeleteSubmissionButton
                label="Delete contact submission?"
                description="This permanently removes the message from your inbox."
                onConfirm={handleDelete}
              />
            </div>
          </div>
        </div>

        <div className="space-y-5 px-5 py-5 md:px-6">
          {isModal && modalHeading ? (
            <div>
              <p className="font-urbanist text-sm font-medium text-muted-foreground">Modal heading</p>
              <p className="mt-1 font-urbanist text-base text-foreground">{modalHeading}</p>
            </div>
          ) : null}
          {data.company ? (
            <div>
              <p className="font-urbanist text-sm font-medium text-muted-foreground">Company</p>
              <p className="mt-1 font-urbanist text-base text-foreground">{data.company}</p>
            </div>
          ) : null}
          {data.job_title ? (
            <div>
              <p className="font-urbanist text-sm font-medium text-muted-foreground">Role</p>
              <p className="mt-1 font-urbanist text-base text-foreground">{data.job_title}</p>
            </div>
          ) : null}
          {showMessage ? (
            <div>
              <p className="font-urbanist text-sm font-medium text-muted-foreground">Message</p>
              <p className="mt-2 whitespace-pre-wrap font-urbanist text-base leading-relaxed text-foreground">
                {data.message}
              </p>
            </div>
          ) : null}
          <div className="border-t border-border pt-5">
            <AdminMailtoButton
              email={data.email}
              subject={mailSubject}
              body={mailBody}
              label="Email sender"
            />
          </div>
        </div>
      </article>

      <article className={adminInternalNotePanelClass}>
        <div className="px-5 py-5 md:px-6">
          <AdminSubmissionNoteEditor
            table="contact_responses"
            submissionId={data.id}
            initialNote={(data as ContactSubmission & { admin_note?: string | null }).admin_note}
            onSaved={() => void queryClient.invalidateQueries({ queryKey: ["admin-contact", id] })}
          />
        </div>
      </article>
      </div>
      </AdminPageReveal>
    </div>
  )
}

export default AdminContactDetail
