import { supabase } from "@/lib/supabase"
import type { SubmissionStatus } from "@/lib/adminSubmissionStatus"

export type DiagnosticSectionScore = { category: string; score: number }

export type DiagnosticStrength = { category: string; score: number; note: string }

export type DiagnosticWeakness = {
  category: string
  score: number
  note: string
  priority: string
}

export type DiagnosticResponseSummary = {
  section_scores: DiagnosticSectionScore[] | null
  summary: string | null
  top3_strengths: DiagnosticStrength[] | null
  top3_weaknesses: DiagnosticWeakness[] | null
  recommendations: string[] | null
  mentor_areas_needed: string[] | null
}

export type CompanyProfileRow = {
  id: string
  created_at: string
  name: string
  work_email: string
  company_name: string
  stage: string | null
  description: string | null
  status?: SubmissionStatus | null
  status_updated_at?: string | null
  admin_note?: string | null
  diagnostic_response?: DiagnosticResponseSummary | null
}

export type ContactRow = {
  id: string
  created_at: string
  first_name: string
  last_name: string
  email: string
  company: string | null
  job_title: string | null
  message: string
  status?: SubmissionStatus | null
  status_updated_at?: string | null
  submission_type?: string | null
  admin_note?: string | null
}

export const fetchContactSubmissions = async (): Promise<ContactRow[]> => {
  const { data, error } = await supabase.from("contact_responses").select("*").order("created_at", { ascending: false })
  if (error) throw error
  return (data ?? []) as ContactRow[]
}

export const fetchDiagnosticSubmissions = async (): Promise<CompanyProfileRow[]> => {
  const { data, error } = await supabase
    .from("company_profiles")
    .select(
      `
      *,
      diagnostic_responses (
        created_at,
        section_scores,
        summary,
        top3_strengths,
        top3_weaknesses,
        recommendations,
        mentor_areas_needed
      )
    `,
    )
    .order("created_at", { ascending: false })

  if (error) throw error

  return (data ?? []).map((row) => {
    const {
      diagnostic_responses: responses,
      ...profile
    } = row as CompanyProfileRow & {
      diagnostic_responses?: Array<
        DiagnosticResponseSummary & {
          created_at: string
        }
      >
    }

    const latestResponse = Array.isArray(responses)
      ? [...responses].sort(
          (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
        )[0]
      : null

    return {
      ...profile,
      diagnostic_response: latestResponse
        ? {
            section_scores: latestResponse.section_scores,
            summary: latestResponse.summary,
            top3_strengths: latestResponse.top3_strengths,
            top3_weaknesses: latestResponse.top3_weaknesses,
            recommendations: latestResponse.recommendations,
            mentor_areas_needed: latestResponse.mentor_areas_needed,
          }
        : null,
    }
  })
}

export const contactDisplayName = (row: ContactRow) =>
  `${row.first_name} ${row.last_name === "." ? "" : row.last_name}`.trim()

export const contactTypeLabel = (row: ContactRow) => {
  if (row.submission_type === "investor") return "Investor notify"
  if (row.submission_type === "modal") return "Priority modal"
  return "Contact"
}

const MODAL_MESSAGE_PREFIX = /^Priority modal form submission\. Source:\s*/i

export const isAutoGeneratedContactMessage = (message: string | null | undefined): boolean => {
  const trimmed = message?.trim() ?? ""
  if (!trimmed) return true
  return MODAL_MESSAGE_PREFIX.test(trimmed)
}

export const parseModalSubmissionSource = (message: string | null | undefined): string | null => {
  const trimmed = message?.trim() ?? ""
  if (!trimmed) return null
  const match = trimmed.match(/^Priority modal form submission\. Source:\s*(.+)$/i)
  return match?.[1]?.trim() || null
}
